org.gradle.daemon=true
org.gradle.jvmargs=-Xms512M -Xmx1G
org.gradle.configureondemand=false
jdkgdxdsVersion=1.10.0
funderbyVersion=0.1.2
digitalVersion=0.6.2
jdkgdxdsInteropVersion=1.10.0.0
juniperVersion=0.6.9
regExodusVersion=0.1.19
graalHelperVersion=2.0.1
enableGraalNative=false
gwtFrameworkVersion=2.11.0
gwtPluginVersion=1.1.29
# suppress inspection "GDXOutdatedVersionGradleProperties"
gdxVersion=1.13.1
cruxVersion=0.1.2
squadVersion=82de10e2b5
#squadVersion=72f9e9a504
